# Generated by Django 4.1.2 on 2022-10-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_persona_fecha_nacimineto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fecha_nacimineto',
            new_name='fecha_nacimiento',
        ),
    ]
